### ISSUE TITLE
no mouse cursor change on dark mode?

### ISSUE THREAD

**Issue by ghost** [t1m0thyj/WDD-scripts#26] opened 2022-11-11 19:24 UTC
no mouse cursor change on dark mode?

no mouse cursor change on dark mode?

**Comment by t1m0thyj** [comment] 2023-02-13 22:55
@bigplayer-ai I don't have time to make a script for this right now, but contributions are welcome 🙂 See the readme for how to [create a new script](https://github.com/t1m0thyj/WDD-scripts#create-new-scripts).

**Comment by bigplayer-ai** [comment] 2023-02-17 15:02
#31

**Comment by t1m0thyj** [comment] 2023-02-20 13:44
Closing as duplicate of #4

**Closed by t1m0thyj** 2023-02-20 13:44 UTC
Labels: new-script
