### ISSUE TITLE
wdd script to change app/system theme stopped working after 22H2 update

### ISSUE THREAD

**Issue by ghost** [t1m0thyj/WDD-scripts#23] opened 2022-09-30 06:36 UTC
wdd script to change app/system theme stopped working after 22H2 update

**Comment by t1m0thyj** [comment] 2023-02-20 13:39
Closing as duplicate of https://github.com/t1m0thyj/WDD-scripts/issues/21 and https://github.com/t1m0thyj/WinDynamicDesktop/issues/427

**Closed by t1m0thyj** 2023-02-20 13:39 UTC
