### ISSUE TITLE
Windows is not respecting theme change.

### ISSUE THREAD

**Issue by bigplayer-ai** [t1m0thyj/WDD-scripts#33] opened 2023-02-19 09:31 UTC
Hey,
There is an issue with multiple people that windows does not respect theme change.
As shown in here:
https://github.com/t1m0thyj/WinDynamicDesktop/issues/427
https://github.com/t1m0thyj/WinDynamicDesktop/issues/463
https://github.com/t1m0thyj/WinDynamicDesktop/issues/480
https://github.com/t1m0thyj/WinDynamicDesktop/issues/493
![Windows is not respecting theme change](https://user-images.githubusercontent.com/119108387/219940117-34e454c5-b7c5-491c-9612-2da78bbc4b9d.png)

I have the same issue using Windows 11 22H2 build 22621.1265.
I think the font color and other system parameters must be called after changing the registry.
Furthermore, I think this is more related to WDD scripts than WDD itself. This issue is more about the System Theme switch/Application Theme switch.
Check my mouse script, How I called system parameters to update the new mouse value.
```
$CSharpSig = @’
[DllImport("user32.dll", EntryPoint = "SystemParametersInfo")]
public static extern bool SystemParametersInfo(
             uint uiAction,
             uint uiParam,
             uint pvParam,
             uint fWinIni);
‘@
$CursorRefresh = Add-Type -MemberDefinition $CSharpSig -Name WinAPICall -Namespace SystemParamInfo –PassThru
$CursorRefresh::SystemParametersInfo(0x0057,0,$null,0)
```
Pull request for the mouse script: 
https://github.com/t1m0thyj/WDD-scripts/pull/31
Mouse script where I called system parameters to update their mouse values: 
https://github.com/t1m0thyj/WDD-scripts/blob/a0994e51bab41a0baeb568fa77ef0c4664958909/ChangeMouseScheme.ps1

You just need to know which API needs to be called to update these values. Maybe use [Process Monitor v3.92](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon)?

**Comment by t1m0thyj** [comment] 2023-02-20 13:40
Closing as duplicate of https://github.com/t1m0thyj/WDD-scripts/issues/21 and https://github.com/t1m0thyj/WinDynamicDesktop/issues/427

**Closed by t1m0thyj** 2023-02-20 13:40 UTC
