### ISSUE TITLE
Virtual space script error

### ISSUE THREAD

**Issue by bigplayer-ai** [t1m0thyj/WDD-scripts#34] opened 2023-02-19 10:25 UTC
Hey,
I receive this error when I run virtual space powershell script:
![image](https://user-images.githubusercontent.com/119108387/219942360-09bc34d4-a81b-429b-b859-e597958dc5dd.png)

**Comment by t1m0thyj** [comment] 2023-02-20 13:46
Closing as duplicate of #30, please reply to that issue with your Windows build number.

**Closed by t1m0thyj** 2023-02-20 13:46 UTC
