### ISSUE TITLE
ChangeWindowsAppTheme and ChangeWindowsSystemTheme not useful for my new PC

### ISSUE THREAD

**Issue by Robert13guo** [t1m0thyj/WDD-scripts#5] opened 2021-01-08 16:44 UTC
Hello,

I recently have a new PC, but it was not worked for me to change the APP and Windows theme automatically.

Any idea what setting I should check?

Robert

**Comment by nick-botticelli** [comment] 2021-01-20 22:24
Same issue, just installed the latest versions as of today and followed the guide on enabling the scripts, and system/app themes do not change when toggling Night Mode or Refresh Wallpaper option. I'm on latest Windows 10 version and using the GitHub release.

**Comment by snowtyler** [comment] 2021-05-20 10:47
With Windows 10 21H1 releasing I formatted my system drive and reinstalled Windows with the latest version. Downloaded the app theme/system theme scripts, installed WDD and dropped the scripts in the folder. It doesn't seem to change the theme anymore.

**Comment by yazan1107** [comment] 2021-11-20 08:52
yes this also happens to me!

**Comment by t1m0thyj** [comment] 2023-02-20 13:38
Closing as duplicate of https://github.com/t1m0thyj/WDD-scripts/issues/33 and https://github.com/t1m0thyj/WinDynamicDesktop/issues/427

**Closed** 2023-02-20 13:38 UTC
